project                  = "devstream-dev-2e76"
project_prefix           = "devstream"
region                   = "us-east4"
environment              = "dev"
user_management_base_url = "https://api-dev.devstream.dsgov.demo.nuvalence.io/um"
